spring:
  cloud:
    function:
      definition: userStatisticAnalysis

    stream:
      bindings:
        userStatisticAnalysis-in-0:
          destination: att.user-statistic-ai-analysis

          group: att-ai-assistance

          content-type: application/json

          consumer:
            max-attempts: 2
            back-off-initial-interval: 2000
            back-off-max-interval: 2000
            back-off-multiplier: 1.0

            retryable-exceptions:
              jakarta.validation.ConstraintViolationException: false
              att.ai.llm.LlmRequestRejectedException: false

      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

          replication-factor: 1

          min-partition-count: 6

        bindings:
          userStatisticAnalysis-in-0:
            consumer:
              enableDlq: true
              dlqName: att.user-statistic-ai-analysis.dlq
