apiVersion: v1
kind: ConfigMap
metadata:
  name: aiassistance-config
  namespace: {{ .Values.namespace }}
data:
  MAIL_PORT: {{ .Values.mail.port | quote }}
  MAIL_SMTP_AUTH: {{ .Values.mail.smtpAuth | quote }}
  MAIL_SMTP_STARTTLS: {{ .Values.mail.starttls | quote }}
  MAIL_ENABLED: {{ .Values.mail.enabled | quote }}

  ATT_AI_ANALYSIS_HISTORYMONTHS: {{ .Values.analysis.historyMonths | quote }}
